/*
 * The default social share card: the EG mark and the name on cream, nothing
 * else. Generated by scripts/generate-og-image.mjs.
 *
 * Every page needs this spelled out, not just the root layout. Next.js
 * replaces the whole `openGraph` object when a segment declares one, so a page
 * that sets its own title and description silently loses the parent's images
 * along with it — which is how link previews ended up showing whichever photo
 * the scraper happened to find in the page body.
 */

export const OG_IMAGE_URL = "/og-image.png";

export const OG_IMAGE = {
  url: OG_IMAGE_URL,
  width: 1200,
  height: 630,
  alt: "Elizabeth's Gift",
} as const;

export const OG_IMAGES = [OG_IMAGE];
